# Generated by Django 2.2.10 on 2020-03-25 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('name', models.CharField(help_text='名称', max_length=128, verbose_name='名称')),
                ('price', models.IntegerField(blank=True, help_text='价格', verbose_name='价格')),
                ('all_num', models.IntegerField(blank=True, help_text='个数', verbose_name='个数')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['-create_time'],
                'permissions': (('apply_good', '可以申请物品'),),
            },
        ),
        migrations.CreateModel(
            name='GoodBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('num', models.IntegerField(default=1, help_text='数量', verbose_name='数量')),
                ('start_t', models.DateField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间')),
                ('end_t', models.DateField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('status', models.IntegerField(choices=[(0, '不通过'), (1, '通过'), (2, '等待')], default=2, help_text='借用状态', verbose_name='借用状态')),
                ('good', models.ForeignKey(blank=True, help_text='物品', null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Good', verbose_name='物品')),
                ('user', models.ForeignKey(blank=True, help_text='借用者', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借用者')),
            ],
            options={
                'ordering': ['-good'],
            },
        ),
        migrations.AddField(
            model_name='good',
            name='user_borrowed',
            field=models.ManyToManyField(blank=True, help_text='借用者', through='goods.GoodBorrow', to=settings.AUTH_USER_MODEL, verbose_name='借用者'),
        ),
    ]
