# Generated by Django 2.2.10 on 2020-03-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='all_num',
            field=models.IntegerField(blank=True, help_text='数量', verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='goodborrow',
            name='status',
            field=models.IntegerField(choices=[(0, '等待审核'), (1, '审核通过'), (2, '驳回')], default=0, help_text='借用状态', verbose_name='借用状态'),
        ),
    ]
