# Generated by Django 2.2.10 on 2020-03-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200330_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodborrow',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='驳回原因', null=True, verbose_name='驳回原因'),
        ),
    ]
