# Generated by Django 2.2.10 on 2020-03-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200313_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerifyCode',
        ),
    ]
