# Generated by Django 2.2.10 on 2020-03-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_verifycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
