# Generated by Django 2.2.10 on 2020-03-20 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProApprove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '不通过'), (1, '通过'), (2, '等待')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('introduction', models.TextField(blank=True, verbose_name='项目介绍')),
                ('is_full', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('plan', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start_t', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('end_t', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_project', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, through='project.ProApprove', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-date'],
                'permissions': (('apply_project', '可以申请项目'),),
            },
        ),
        migrations.AddField(
            model_name='proapprove',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='proapprove',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
