# Generated by Django 2.2.10 on 2020-03-30 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proapprove',
            options={'verbose_name': '审核状态', 'verbose_name_plural': '审核状态'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-create_time'], 'permissions': (('apply_project', '可以申请项目'),), 'verbose_name': '项目信息', 'verbose_name_plural': '项目信息'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AddField(
            model_name='proapprove',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='proapprove',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='proapprove',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='驳回原因', null=True, verbose_name='驳回原因'),
        ),
        migrations.AddField(
            model_name='proapprove',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='proapprove',
            name='project',
            field=models.ForeignKey(blank=True, help_text='项目', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='proapprove',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '驳回')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='proapprove',
            name='user',
            field=models.ForeignKey(help_text='成员', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_t',
            field=models.DateField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.TextField(blank=True, help_text='项目简介', verbose_name='项目简介'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='激活状态', verbose_name='激活状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_finish',
            field=models.BooleanField(choices=[(False, '未完成'), (True, '已完成')], default=False, help_text='已完成', verbose_name='已完成'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_full',
            field=models.BooleanField(default=False, help_text='人员名额已满', verbose_name='人员名额已满'),
        ),
        migrations.AlterField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='项目负责人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_project', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='项目名称', max_length=128, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='plan',
            field=models.IntegerField(default=0, help_text='进度', verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_t',
            field=models.DateField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='项目成员', through='project.ProApprove', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('purpose', models.CharField(help_text='申请目的', max_length=200, verbose_name='申请目的')),
                ('status', models.BooleanField(default=False, help_text='申请状态', verbose_name='申请状态')),
                ('money', models.DecimalField(decimal_places=2, default=0.0, help_text='数额', max_digits=4, verbose_name='数额')),
                ('project', models.ForeignKey(blank=True, help_text='项目团队', null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目团队')),
            ],
            options={
                'verbose_name': '资金申请',
                'verbose_name_plural': '资金申请',
                'permissions': (('apply_finding', '可以申请资金'),),
            },
        ),
    ]
