# Generated by Django 2.2.10 on 2020-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200330_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
        migrations.AddField(
            model_name='project',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='驳回原因', null=True, verbose_name='驳回原因'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, '待审核'), (1, '审核通过'), (2, '驳回')], default=0, help_text='状态', verbose_name='状态'),
        ),
    ]
