# Generated by Django 2.2.10 on 2020-04-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('title', models.CharField(blank=True, help_text='周报标题', max_length=100, verbose_name='周报标题')),
                ('content', models.TextField(help_text='周报内容', verbose_name='周报内容')),
                ('week_count', models.IntegerField(default=14, help_text='周次', verbose_name='周次')),
                ('owner', models.ForeignKey(blank=True, help_text='所有者', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报',
            },
        ),
    ]
