# Generated by Django 2.2.10 on 2020-04-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekreport',
            name='remark',
            field=models.CharField(blank=True, help_text='备注', max_length=100, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='weekreport',
            name='week_count',
            field=models.IntegerField(default=5, help_text='周次', verbose_name='周次'),
        ),
    ]
